// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/model — DO NOT EDIT.
// Regenerate: make types
/* eslint-disable */
import type { HastNode } from "./index";

//////////
// source: activity.go

/**
 * ActivityType discriminates the kinds of entries in a user's activity stream.
 */
export type ActivityType = string;
/**
 * ActivityReaction records that someone added an emoji reaction to one of
 * the user's own messages.
 */
export const ActivityReaction: ActivityType = "reaction";
/**
 * ActivityReminder records a "remind me about this message" reminder that
 * has fired at its scheduled time.
 */
export const ActivityReminder: ActivityType = "reminder";
/**
 * ActivityItem is one entry in a user's personal activity stream (Slack-style
 * Activity tab). It is a denormalized, self-contained hint: it carries enough
 * context (preview + parent + message id) to render a row and deep-link to the
 * source message without any further lookups, so the stream survives even if the
 * underlying message is later edited or deleted.
 */
export interface ActivityItem {
  id: string;
  type: ActivityType;
  createdAt: string /* RFC3339 */;
  messageID: string;
  parentID: string;
  parentType: string; // "channel" | "conversation"
  /**
   * ChannelSlug is set for channel parents so the client can build a slug URL
   * without resolving the channel; empty for conversations.
   */
  channelSlug?: string;
  /**
   * MessagePreview is a short plain-text excerpt of the source message.
   */
  messagePreview?: string;
  /**
   * ActorID / Emoji are set for ActivityReaction: who reacted and with what.
   */
  actorID?: string;
  emoji?: string;
}
/**
 * Reminder is a scheduled "remind me about this message" entry. It lives until
 * it fires (or is cancelled), at which point it produces an ActivityReminder
 * item in the owner's activity stream plus a desktop/mobile alert.
 */
export interface Reminder {
  id: string;
  userID: string;
  messageID: string;
  parentID: string;
  parentType: string; // "channel" | "conversation"
  channelSlug?: string;
  messagePreview?: string;
  remindAt: string /* RFC3339 */;
  createdAt: string /* RFC3339 */;
}

//////////
// source: attachment.go

/**
 * Attachment is a file uploaded to object storage and tracked in DynamoDB so
 * messages can reference it by ID. SHA256 dedupes uploads of the same content
 * to a single S3 object; MessageIDs is the (Dynamo string-set-backed) refcount
 * — when it drops to zero the S3 object and Attachment row are removed.
 */
export interface Attachment {
  id: string;
  sha256: string;
  size: number /* int64 */;
  contentType: string;
  filename: string;
  url?: string; // resolved at fetch time, inline (used by <img>/preview)
  downloadURL?: string; // resolved at fetch time, forces Content-Disposition: attachment
  thumbnailURL?: string;
  squareThumbnailURL?: string;
  /**
   * Width and Height are the intrinsic pixel dimensions of an
   * image attachment. Detected at upload time from the image's
   * own headers and persisted so the frontend can render the
   * <img> with explicit width/height attributes — that reserves
   * the layout box on first paint and stops the message list
   * from shifting as the image decodes. Zero for non-image
   * attachments and for image attachments uploaded before this
   * field existed (lazy-backfilled on next read).
   */
  width?: number /* int */;
  height?: number /* int */;
  createdBy: string;
  createdAt: string /* RFC3339 */;
}

//////////
// source: auth.go

export interface TokenClaims {
  RegisteredClaims: any /* jwt.RegisteredClaims */;
  uid: string;
  email: string;
  name: string;
  role: SystemRole;
}
export interface RefreshToken {
  tokenHash: string;
  userID: string;
  expiresAt: string /* RFC3339 */;
  createdAt: string /* RFC3339 */;
  /**
   * RotatedAt marks the moment this token was used and superseded by a
   * successor. A rotated token is NOT deleted: the Set-Cookie carrying its
   * successor rides exactly one HTTP response, and on mobile networks that
   * response is regularly lost — the client then legitimately retries with
   * the only token it ever received. Deleting on rotation turned every
   * lost response into a forced re-login (see AuthService.RefreshAccessToken
   * for the reuse rules that keep rotation's replay protection intact).
   */
  rotatedAt?: string /* RFC3339 */;
  /**
   * SupersededBy is the hash of the successor issued when this token was
   * rotated. Reuse of a rotated token is allowed ONLY while that successor
   * is itself unused — a lost response means the successor's raw value was
   * destroyed with it, so nobody can ever present it.
   */
  supersededBy?: string;
}

//////////
// source: bot.go

/**
 * BotTokenPrefix marks a bearer credential as a bot API token rather than a
 * session JWT. The auth middleware routes on this prefix, which is safe because
 * a JWT always begins "eyJ" (the base64url of `{"`). External integrations may
 * pattern-match on it, so it is permanent API surface.
 */
export const BotTokenPrefix = "exbot_";
/**
 * BotUserIDPrefix namespaces bot user IDs. It keeps a bot's ID visually
 * distinct from a human's bare ULID in logs and message authorship, and it
 * guarantees a bot can never collide with the non-User sentinel author IDs
 * ("webhook", "cliffy") that predate bot accounts.
 */
export const BotUserIDPrefix = "bot_";
/**
 * BotTransport selects the wire format ex uses to POST an event to an external
 * bot's callback URL.
 */
export type BotTransport = string;
/**
 * BotTransportEx is ex's own JSON event, authenticated by an HMAC
 * X-Ex-Signature header. The default for a bot created without an explicit
 * transport, and the only option before MM compatibility landed.
 */
export const BotTransportEx: BotTransport = "ex";
/**
 * BotTransportMattermost is Mattermost's outgoing-webhook format:
 * form-encoded fields with the shared secret carried as the body's `token`.
 * An unmodified Mattermost outgoing-webhook receiver works against this.
 */
export const BotTransportMattermost: BotTransport = "mattermost";
/**
 * BotTriggerWhen selects where a trigger word must appear in a message for the
 * bot to fire. It mirrors Mattermost's `trigger_when` on outgoing webhooks.
 */
export type BotTriggerWhen = number /* int */;
/**
 * BotTriggerWhenStartsWith fires only when the message *begins* with the
 * trigger word. Mattermost's default, and ex's.
 */
export const BotTriggerWhenStartsWith: BotTriggerWhen = 0;
/**
 * BotTriggerWhenContains fires when the trigger word appears anywhere in the
 * message as a standalone word.
 */
export const BotTriggerWhenContains: BotTriggerWhen = 1;
/**
 * BotAccount is the admin-facing metadata for a bot identity. The bot's actual
 * identity — what makes it a channel member, a message author, and a mention
 * target — is a real User row whose ID equals UserID here; this record only
 * carries the fields a human user has no use for.
 */
export interface BotAccount {
  user_id: string;
  name: string;
  description?: string;
  created_by: string;
  create_at: string /* RFC3339 */;
  update_at: string /* RFC3339 */;
  /**
   * Outgoing-webhook transport: when CallbackURL is set, this is an EXTERNAL
   * bot — ex POSTs each @mention/trigger-word event to CallbackURL and posts
   * the response back. Empty → in-process/none.
   */
  callback_url?: string;
  /**
   * Transport is the wire format for CallbackURL. Empty means BotTransportEx.
   */
  transport?: BotTransport;
  /**
   * TriggerWords fire the bot on a message that is not an @mention — MM's
   * outgoing-webhook trigger model, which is how most existing MM bots are
   * invoked. Matched case-insensitively as whole words.
   */
  trigger_words?: string[];
  /**
   * TriggerWhen selects start-of-message (default) vs anywhere matching.
   */
  trigger_when?: BotTriggerWhen;
}
/**
 * BotToken is a revocable bearer credential for a BotAccount. Only the SHA-256
 * hash of the secret is persisted (TokenHash, never serialized): the plaintext
 * is returned once at issuance and is unrecoverable afterwards, so a leaked
 * database dump can't be replayed against the API.
 */
export interface BotToken {
  /**
   * TokenID is the admin-visible handle used to revoke this token, so the UI
   * never has to hold (or display) the hash.
   */
  token_id: string;
  bot_user_id: string;
  label?: string;
  create_at: string /* RFC3339 */;
  last_used_at?: string /* RFC3339 */;
  revoked_at?: string /* RFC3339 */;
}

//////////
// source: channel.go

export type ChannelType = string;
export const ChannelTypePublic: ChannelType = "public";
export const ChannelTypePrivate: ChannelType = "private";
export type ChannelRole = number /* int */;
export const ChannelRoleMember: ChannelRole = 1;
export const ChannelRoleAdmin: ChannelRole = 2;
export const ChannelRoleOwner: ChannelRole = 3;
export interface Channel {
  id: string;
  name: string;
  slug: string;
  description?: string;
  type: ChannelType;
  createdBy: string;
  archived: boolean;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
  /**
   * MessageSeq is a monotonic counter bumped once per top-level human
   * message (not thread replies, not system events). Paired with each
   * member's UserChannel.LastReadSeq it yields an exact, O(1) unread count
   * without per-member writes or count queries. Starts at 0, so on rollout
   * every member is "caught up" and only new messages count — no backfill.
   */
  messageSeq?: number /* int64 */;
}

//////////
// source: command.go

/**
 * ExternalCommand is an admin-registered slash command backed by an HTTP
 * integration, in Mattermost's slash-command shape: ex POSTs the invocation to
 * RequestURL and posts (or shows) whatever comes back.
 * It is distinct from ex's built-in commands, which are compiled in and
 * registered at wiring time (see service.Command). Both appear in one list to
 * clients, so the composer's "/" autocomplete does not care which is which.
 */
export interface ExternalCommand {
  id: string;
  /**
   * Trigger is the word after the slash, without it — "deploy" for "/deploy".
   * Unique across all commands, built-in included, and always lowercase.
   */
  trigger: string;
  /**
   * Title and Description are what the "/" autocomplete shows.
   */
  title?: string;
  description?: string;
  /**
   * AutocompleteHint describes the arguments, e.g. "[service] [version]".
   */
  autocomplete_hint?: string;
  /**
   * RequestURL is the integration endpoint; must be a public https URL.
   */
  request_url: string;
  /**
   * Method is "P" (POST, default) or "G" (GET), matching MM's field.
   */
  method?: string;
  /**
   * BotUserID, when set, is the bot account an in-channel response is authored
   * by — so the post has a real bot identity behind it rather than the generic
   * webhook sentinel. Optional.
   */
  bot_user_id?: string;
  /**
   * Username / IconURL override the display identity of an in-channel response,
   * as MM's command config does.
   */
  username?: string;
  icon_url?: string;
  created_by: string;
  create_at: string /* RFC3339 */;
  update_at: string /* RFC3339 */;
}
/**
 * Command HTTP methods, matching Mattermost's single-letter field.
 */
export const CommandMethodPost = "P";
/**
 * Command HTTP methods, matching Mattermost's single-letter field.
 */
export const CommandMethodGet = "G";

//////////
// source: conversation.go

export type ConversationType = string;
export const ConversationTypeDM: ConversationType = "dm";
export const ConversationTypeGroup: ConversationType = "group";
export interface Conversation {
  id: string;
  type: ConversationType;
  name?: string; // for groups
  participantIDs: string[];
  createdBy: string;
  /**
   * Activated becomes true once the first message is sent. Until then, the
   * conversation is hidden from non-creator participants.
   */
  activated: boolean;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
  /**
   * MessageSeq is the per-conversation monotonic counter bumped once per
   * top-level message — the same unread mechanism channels use (see
   * model.Channel.MessageSeq). Paired with each member's
   * UserConversation.LastReadSeq it yields exact unread counts.
   */
  messageSeq?: number /* int64 */;
}

//////////
// source: draft.go

export interface MessageDraft {
  id: string;
  userID: string;
  parentID: string;
  parentType: string;
  parentMessageID?: string;
  body: string;
  attachmentIDs?: string[];
  updatedAt: string /* RFC3339 */;
  createdAt: string /* RFC3339 */;
  /**
   * Gen is the SERVER-assigned generation token for optimistic concurrency:
   * every accepted write mints a new one, and a save or clear is accepted
   * only when the client presents the generation it acted on (empty = "no
   * draft exists"). Ordering is decided entirely server-side — client
   * clocks play no part — so a delayed, stale, or hostile client write can
   * never supersede a later clear or send. Pre-gen rows report "legacy".
   */
  gen: string;
}

//////////
// source: emoji.go

/**
 * CustomEmoji represents a workspace-uploaded custom emoji that can be
 * referenced in messages or reactions as :name:.
 * ImageKey is the persistent S3 key. The service re-signs ImageURL on
 * every List call from the key so the frontend never has to deal with
 * expired presigned URLs (the bug where custom emojis broke after 7
 * days). ImageURL is sent to clients but not relied on for storage.
 */
export interface CustomEmoji {
  name: string;
  imageURL: string;
  createdBy: string;
  createdAt: string /* RFC3339 */;
  /**
   * GettingWorkDone pins the emoji into the picker's themed
   * "Getting Work Done" shelf; set on the custom-emoji upload page.
   */
  gettingWorkDone: boolean;
}

//////////
// source: invite.go

export interface Invite {
  token: string;
  email: string;
  inviterID: string;
  channelIDs?: string[];
  expiresAt: string /* RFC3339 */;
  createdAt: string /* RFC3339 */;
}

//////////
// source: membership.go

/**
 * ChannelMembership represents a user's membership in a channel (stored on channel side).
 */
export interface ChannelMembership {
  channelID: string;
  userID: string;
  role: ChannelRole;
  displayName: string; // denormalized
  joinedAt: string /* RFC3339 */;
}
/**
 * UserChannel represents a channel from the user's perspective (stored on user side).
 */
export interface UserChannel {
  userID: string;
  channelID: string;
  channelName: string;
  channelType: ChannelType;
  role: ChannelRole;
  joinedAt: string /* RFC3339 */;
  lastReadMsgID?: string;
  /**
   * LastReadSeq is the Channel.MessageSeq value this user had consumed as
   * of their last read. unread count = max(0, Channel.MessageSeq -
   * LastReadSeq); unread = count > 0. Set to the channel's current seq on
   * join, on read, and when the user sends (posting marks the channel read
   * for the author). Persisted on the user-side row only — it's per-user.
   */
  lastReadSeq?: number /* int64 */;
  /**
   * Unread / UnreadCount are read-time enrichments computed in
   * ListUserChannels from the seq pair above — never persisted (mirrors
   * UserConversation.Unread).
   */
  unread?: boolean;
  unreadCount?: number /* int */;
  /**
   * UnreadNotifyCount counts unread messages that actually ALERTED this
   * user per their notification rules (mentions, keywords, "all messages"
   * level; mute suppresses) — the sidebar's numeric badge. Plain unread
   * messages only set the Unread indicator. Persisted (incremented by the
   * notifier for each alerted recipient, reset alongside LastReadSeq)
   * because the notification decision is made once, server-side, at send
   * time and can't be recomputed cheaply at read time.
   */
  unreadNotifyCount?: number /* int64 */;
  /**
   * Muted suppresses notifications (sound + browser popup) for this
   * channel without unsubscribing the user. Real-time event delivery is
   * unaffected; only the notifier respects this flag.
   */
  muted?: boolean;
  /**
   * Favorite pins the channel to the "Favorites" sidebar section. Per
   * user — flipping it here doesn't affect anyone else's view.
   */
  favorite?: boolean;
  /**
   * CategoryID assigns the channel to a user-defined sidebar category;
   * empty string means "no category" (lands under the default "Other"
   * section). The category record itself lives in UserChannelCategory.
   */
  categoryID?: string;
  /**
   * SidebarPosition is a sparse per-user ordering key inside the
   * channel's current sidebar bucket.
   */
  sidebarPosition?: number /* int */;
  /**
   * Per-channel notification preference overrides. A nil pointer means
   * "inherit the user's account-level NotificationSettings" and is stored
   * as an absent attribute. ResolveNotificationPrefs folds these onto the
   * account baseline. Keywords are global (account-only) and not overridable
   * here. Muted (above) is independent and always suppresses everything.
   */
  desktopLevel?: NotificationLevel;
  mobileLevel?: MobileNotificationLevel;
  threadReplies?: boolean;
  ignoreGroupMentions?: boolean;
  followAllThreads?: boolean;
}
/**
 * UserChannelCategory is a user-defined grouping for the sidebar. Users
 * with 100+ channels create categories like "Engineering" or "Customer
 * support" and assign channels to them so the sidebar stays navigable.
 * Categories are per-user — there's no shared workspace concept.
 */
export interface UserChannelCategory {
  userID: string;
  id: string;
  name: string;
  position: number /* int */;
  createdAt: string /* RFC3339 */;
}
/**
 * UserConversation represents a conversation from the user's perspective.
 */
export interface UserConversation {
  userID: string;
  conversationID: string;
  type: ConversationType;
  displayName: string; // other user's name for DM, group name for group
  participantIDs: string[];
  createdBy?: string;
  activated: boolean;
  joinedAt: string /* RFC3339 */;
  updatedAt?: string /* RFC3339 */;
  lastReadMsgID?: string;
  /**
   * LastReadSeq mirrors UserChannel.LastReadSeq: unread = Conversation.MessageSeq
   * - LastReadSeq. The same exact-count seq model backs channels and
   * conversations alike (no more Redis unread boolean).
   */
  lastReadSeq?: number /* int64 */;
  /**
   * Unread / UnreadCount are read-time enrichments computed in
   * ListUserConversations from the seq pair — never persisted.
   */
  unread?: boolean;
  unreadCount?: number /* int */;
  /**
   * UnreadNotifyCount mirrors UserChannel.UnreadNotifyCount: unread
   * messages that actually alerted this user (DM messages always do unless
   * muted), maintained by the notifier and reset alongside LastReadSeq.
   */
  unreadNotifyCount?: number /* int64 */;
  /**
   * AvatarURL and UserStatus are read-time enrichments for DM sidebar rows.
   * They are intentionally not persisted so profile changes stay single
   * sourced from the User record.
   */
  avatarURL?: string;
  userStatus?: UserStatus;
  profileResolved?: boolean;
  /**
   * Favorite pins this DM/group to the user's "Favorites" sidebar
   * section. Same per-user semantics as on UserChannel.
   */
  favorite?: boolean;
  /**
   * CategoryID assigns this DM/group to one of the user's sidebar
   * categories. The same SidebarCategory namespace holds both channels
   * and conversations so a category like "Engineering" can hold both
   * #eng-channel and a DM with the team lead.
   */
  categoryID?: string;
  /**
   * SidebarPosition is a sparse per-user ordering key inside the
   * conversation's current sidebar bucket.
   */
  sidebarPosition?: number /* int */;
}

//////////
// source: message.go

export interface Message {
  id: string;
  parentID: string; // channel or conversation ID
  parentType?: string;
  authorID: string;
  body: string;
  system?: boolean;
  parentMessageID?: string; // root message of the thread
  replyCount?: number /* int */; // count of replies (only set on root messages)
  lastReplyAt?: string /* RFC3339 */; // timestamp of the latest reply (only set on root messages)
  /**
   * RecentReplyAuthorIDs holds up to 3 most-recent distinct author IDs
   * for the thread, newest first. Used by the client to render an
   * avatar stack on the thread-action bar without re-fetching the full
   * thread. Only set on root messages.
   */
  recentReplyAuthorIDs?: string[];
  reactions?: { [key: string]: string[]}; // emoji -> userIDs that reacted
  attachmentIDs?: string[]; // ordered list of attachments referenced by this message
  pinned?: boolean; // pinned to the parent (channel/conversation)
  pinnedAt?: string /* RFC3339 */;
  pinnedBy?: string;
  createdAt: string /* RFC3339 */;
  editedAt?: string /* RFC3339 */;
  /**
   * Deleted is set on soft-delete: the row stays in the list so the
   * thread structure (replies referencing this ID) is preserved, but
   * Body / AttachmentIDs / Reactions are cleared and the client
   * renders a "(Message deleted)" placeholder.
   */
  deleted?: boolean;
  /**
   * NoUnfurl suppresses the link-preview card the client would
   * otherwise render below the body. Set when the author dismisses
   * the unfurl — the suppression is global (every viewer sees it
   * off), which is what authors expect when the preview is wrong.
   */
  noUnfurl?: boolean;
  /**
   * Rendered is the server-rendered hast tree for Body — populated
   * at read time, never persisted (the `dynamodbav:"-"` tag keeps
   * it out of DDB). Frontend consumers prefer this over re-parsing
   * the markdown source per render. nil means "not yet rendered"
   * (legacy messages, intermediate API paths) — clients fall back
   * to client-side parsing.
   */
  rendered?: HastNode;
  /**
   * Incoming webhook messages can override the displayed author and carry
   * Mattermost-compatible message attachments. AuthorID remains a stable
   * bot identifier for notifications/search, while these fields drive rendering.
   */
  webhookUsername?: string;
  webhookAvatarURL?: string;
  webhookIconEmoji?: string; // emoji name (no colons) from icon_emoji; rendered as the avatar
  messageAttachments?: MessageAttachment[];
}
export interface MessageAttachment {
  fallback?: string;
  color?: string;
  pretext?: string;
  text?: string;
  author_name?: string;
  author_link?: string;
  author_icon?: string;
  title?: string;
  title_link?: string;
  fields?: MessageAttachmentField[];
  image_url?: string;
  /**
   * ImageWidth/ImageHeight are the intrinsic pixel dimensions of the
   * S3-cached image_url, captured server-side at send time so the
   * client can render <img width height> and avoid layout shift in the
   * virtualised message list. Not part of the inbound webhook payload.
   */
  image_width?: number /* int */;
  image_height?: number /* int */;
  thumb_url?: string;
  footer?: string;
  footer_icon?: string;
  /**
   * Actions are interactive controls (buttons / select menus) rendered under
   * the attachment, in Mattermost's interactive-message shape. Clicking one
   * calls back into the integration that posted the attachment.
   */
  actions?: MessageAction[];
}
export interface MessageAttachmentField {
  title?: string;
  value?: string;
  short?: boolean;
}
/**
 * MessageAction types, matching Mattermost's interactive message actions.
 */
export const MessageActionTypeButton = "button";
/**
 * MessageAction types, matching Mattermost's interactive message actions.
 */
export const MessageActionTypeSelect = "select";
/**
 * MessageAction is one interactive control on an attachment. The client sends
 * back only the action's ID; ex resolves the stored Integration server-side and
 * calls it. That indirection is deliberate — see Integration below.
 */
export interface MessageAction {
  /**
   * ID identifies this action within the message. Supplied by the integration
   * or minted at post time so it is always non-empty and unique per message.
   */
  id: string;
  name: string;
  /**
   * Type is MessageActionTypeButton (default) or MessageActionTypeSelect.
   */
  type?: string;
  /**
   * Style is MM's cosmetic hint: "default", "primary", "success", "good",
   * "warning", "danger", or a hex colour. Rendered as a button variant.
   */
  style?: string;
  /**
   * Disabled renders the control as non-interactive.
   */
  disabled?: boolean;
  /**
   * Options are the choices for a select action.
   */
  options?: MessageActionOption[];
}
/**
 * MessageActionOption is one choice in a select action.
 */
export interface MessageActionOption {
  text: string;
  value: string;
}
/**
 * ActionIntegration is the server-side callback target of a MessageAction.
 */
export interface ActionIntegration {
  url: string;
  /**
   * Context is arbitrary integration-owned JSON echoed back on invocation. It
   * is how an integration knows *which* thing the button referred to without
   * ex understanding its domain.
   */
  context?: { [key: string]: any};
}

//////////
// source: notification_settings.go

/**
 * NotificationLevel controls which messages fire a user-facing notification
 * (sound + popup on desktop; push on mobile). It is deliberately small: the
 * "all" firehose or the quiet "mentions, DMs & keywords only" default.
 */
export type NotificationLevel = string;
export const NotificationLevelAll: NotificationLevel = "all"; // every message
export const NotificationLevelMentions: NotificationLevel = "mentions"; // mentions, DMs, keywords only
/**
 * MobileNotificationLevel mirrors NotificationLevel but adds a "default"
 * sentinel meaning "use the same rule as desktop". This is the default so a
 * user only has to configure mobile separately when they actually want to.
 */
export type MobileNotificationLevel = string;
export const MobileNotificationDefault: MobileNotificationLevel = "default"; // same as desktop
export const MobileNotificationAll: MobileNotificationLevel = "all";
export const MobileNotificationMentions: MobileNotificationLevel = "mentions";
/**
 * NotificationSettings is a user's account-level notification baseline. Every
 * channel inherits these unless overridden per-channel (see UserChannel's
 * pointer override fields). Keywords live only here — they are global, matched
 * case-insensitively on word boundaries so "mentions, DMs & keywords only" can
 * still surface messages a user cares about.
 */
export interface NotificationSettings {
  desktopLevel: NotificationLevel;
  mobileLevel: MobileNotificationLevel;
  threadReplies: boolean;
  ignoreGroupMentions: boolean;
  followAllThreads: boolean;
  keywords?: string[];
}
/**
 * ChannelNotificationOverride carries the per-channel override values a user
 * submits. A nil field means "inherit the account default" — persisted as an
 * absent attribute so the resolver falls back to the account setting.
 */
export interface ChannelNotificationOverride {
  desktopLevel?: NotificationLevel;
  mobileLevel?: MobileNotificationLevel;
  threadReplies?: boolean;
  ignoreGroupMentions?: boolean;
  followAllThreads?: boolean;
}

//////////
// source: settings.go

/**
 * WorkspaceSettings holds workspace-wide knobs an admin controls. The
 * document is keyed in the single-table store under a fixed PK/SK so
 * there's exactly one record. Settings are read on every upload, so
 * callers should rely on the cache layer.
 */
export interface WorkspaceSettings {
  /**
   * MaxUploadBytes is the maximum file size accepted by the
   * attachment-upload endpoint. 0 means "use the built-in default".
   */
  maxUploadBytes: number /* int64 */;
  /**
   * AllowedExtensions is a lowercase list (without the leading dot)
   * of file extensions that may be uploaded. Empty list means "use
   * the built-in default".
   */
  allowedExtensions: string[];
  /**
   * GiphyAPIKey, when non-empty, enables the Giphy picker in the
   * composer. GIPHY requires client-side API/media requests, so this
   * browser key is sent to authenticated clients that can use the picker.
   */
  giphyAPIKey?: string;
}
/**
 * DefaultMaxUploadBytes is the fallback ceiling when the workspace hasn't
 * overridden it (50 MiB).
 */
export const DefaultMaxUploadBytes: number /* int64 */ = 50 * 1024 * 1024;

//////////
// source: thread_follow.go

/**
 * ThreadFollow is a per-user override for thread participation.
 * Following=true explicitly adds a thread to /threads and thread-reply
 * notifications. Following=false suppresses implicit participation from
 * authored roots/replies without suppressing direct mentions.
 */
export interface ThreadFollow {
  userID: string;
  parentID: string;
  parentType: string;
  threadRootID: string;
  following: boolean;
  updatedAt: string /* RFC3339 */;
}

//////////
// source: user.go

export type SystemRole = string;
export const SystemRoleAdmin: SystemRole = "admin";
export const SystemRoleMember: SystemRole = "member";
export const SystemRoleGuest: SystemRole = "guest";
/**
 * AuthProvider records how a user authenticates. It is authoritative for
 * "is this user managed by an external IdP?" — OIDC users have their display
 * name owned by the IdP and cannot rename themselves locally.
 */
export type AuthProvider = string;
export const AuthProviderOIDC: AuthProvider = "oidc";
export const AuthProviderGuest: AuthProvider = "guest";
/**
 * AuthProviderBot marks a bot account: a real user row that authenticates
 * with a bot API token instead of a session JWT, so it can hold channel
 * memberships and author messages like any other member.
 */
export const AuthProviderBot: AuthProvider = "bot";
export interface User {
  id: string;
  email: string;
  displayName: string;
  avatarURL?: string; // presigned URL, regenerated on each fetch
  systemRole: SystemRole;
  authProvider?: AuthProvider;
  emojiSkinTone?: string;
  userStatus?: UserStatus;
  timeZone?: string;
  /**
   * NotificationSettings is the user's account-level notification baseline
   * (desktop/mobile levels, thread replies, group mentions, follow-all, and
   * the global keyword list). Nil means the user has never customised it and
   * DefaultNotificationSettings applies.
   */
  notificationSettings?: NotificationSettings;
  status: string; // "active", "deactivated"
  lastSeenAt?: string /* RFC3339 */;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
  /**
   * Phone and Manager are directory attributes synced from Microsoft 365
   * at SSO login when the Graph integration is enabled. They are owned by
   * the directory (read-only in the app) and shown on profile surfaces.
   */
  phone?: string;
  manager?: UserManager;
}
/**
 * UserManager is a lightweight reference to a user's manager from the
 * employee directory. UserID is set when the manager is also an Ex user
 * (matched by email) so clients can link to their profile.
 */
export interface UserManager {
  displayName: string;
  email?: string;
  userID?: string;
}
export interface UserStatus {
  emoji: string;
  text: string;
  clearAt?: string /* RFC3339 */;
}

//////////
// source: user_state.go

export type UserStateKind = string;
export const UserStateThreadNotification: UserStateKind = "thread_notification";
export const UserStateThreadSeen: UserStateKind = "thread_seen";
export const UserStateHiddenConversation: UserStateKind = "hidden_conversation";
export interface UserStateItem {
  userID: string;
  kind: UserStateKind;
  targetID: string;
  parentID?: string;
  parentType?: string;
  threadRootID?: string;
  seenAt?: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
}
export interface UserState {
  threadNotifications: string[];
  threadSeen: { [key: string]: string};
  hiddenConversations: string[];
}

//////////
// source: webhook.go

export interface IncomingWebhook {
  id: string;
  title: string;
  description?: string;
  channelID: string;
  channelName?: string;
  channelSlug?: string;
  lockToChannel: boolean;
  username?: string;
  profileImageURL?: string;
  createdBy: string;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
}
