// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"
)

// Ensure, that ConversationActivatorMock does implement ConversationActivator.
// If this is not the case, regenerate this file with moq.
var _ ConversationActivator = &ConversationActivatorMock{}

// ConversationActivatorMock is a mock implementation of ConversationActivator.
//
//	func TestSomethingThatUsesConversationActivator(t *testing.T) {
//
//		// make and configure a mocked ConversationActivator
//		mockedConversationActivator := &ConversationActivatorMock{
//			ActivateFunc: func(ctx context.Context, convID string) error {
//				panic("mock out the Activate method")
//			},
//		}
//
//		// use mockedConversationActivator in code that requires ConversationActivator
//		// and then make assertions.
//
//	}
type ConversationActivatorMock struct {
	// ActivateFunc mocks the Activate method.
	ActivateFunc func(ctx context.Context, convID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Activate holds details about calls to the Activate method.
		Activate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConvID is the convID argument value.
			ConvID string
		}
	}
	lockActivate sync.RWMutex
}

// Activate calls ActivateFunc.
func (mock *ConversationActivatorMock) Activate(ctx context.Context, convID string) error {
	callInfo := struct {
		Ctx    context.Context
		ConvID string
	}{
		Ctx:    ctx,
		ConvID: convID,
	}
	mock.lockActivate.Lock()
	mock.calls.Activate = append(mock.calls.Activate, callInfo)
	mock.lockActivate.Unlock()
	if mock.ActivateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ActivateFunc(ctx, convID)
}

// ActivateCalls gets all the calls that were made to Activate.
// Check the length with:
//
//	len(mockedConversationActivator.ActivateCalls())
func (mock *ConversationActivatorMock) ActivateCalls() []struct {
	Ctx    context.Context
	ConvID string
} {
	var calls []struct {
		Ctx    context.Context
		ConvID string
	}
	mock.lockActivate.RLock()
	calls = mock.calls.Activate
	mock.lockActivate.RUnlock()
	return calls
}
